#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

MKDIR_OUTPUT=/tmp/mkdir.log
OWNER=${OWNER-$USER}

while test ${#} -gt 0
do
  VARIABLE=$1
  if [[ "$VARIABLE" == *"/"* ]]; then
    DIR=$VARIABLE
  else
    if [[ -z "${!VARIABLE:-}" ]]; then
      error "Unknown variable $VARIABLE, make sure it is export'ed"
      exit 1
    fi
    DIR=${!VARIABLE}
  fi

  if [ ! -e $DIR ] ; then
    SCRIPT_OUTPUT=$(mkdir -p ${DIR} > $MKDIR_OUTPUT 2>&1)
    ERROR="Unable to mkdir -p ${DIR} due to ..." ./bits/bootstrap/failonerrors $? $MKDIR_OUTPUT
    [ $? -ne 0 ] && exit 1
    debug "  -- Created $VARIABLE ($DIR)"

    OWNER=$OWNER ./bits/bootstrap/chownif $DIR
    [ $? -ne 0 ] && exit 1
  else
    debug "  -- Re-using $VARIABLE ($DIR)"
  fi
  shift
done


