#!/bin/bash
[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging

WGET_PARAMS=${WGET_PARAMS-""}
TARGET_NAME=${TARGET_NAME-$SRC_NAME}
LOCAL_FILE=$SRC_DIR/$TARGET_NAME
WGET_HEADER=${WGET_HEADER-none}


if [[ ! -e $LOCAL_FILE ]]; then
  notify "  -- Downloading $NAME from $REMOTE_URL/$SRC_NAME to $LOCAL_FILE"

  if [[ "$WGET_HEADER" == "none" ]]; then
    (cd $SRC_DIR && wget --quiet $WGET_PARAMS -O $TARGET_NAME $REMOTE_URL/$SRC_NAME)
  else
    (cd $SRC_DIR && wget --quiet $WGET_PARAMS --header "$WGET_HEADER" -O $TARGET_NAME $REMOTE_URL/$SRC_NAME)
  fi

  if [[ ! -e $LOCAL_FILE ]]; then
    error "Unable to download $REMOTE_URL/$SRC_NAME to $SRC_DIR/$TARGET_NAME"
    exit 1
  fi

else
  debug "  -- Already downloaded $NAME to ${LOCAL_FILE}"
fi

